const bankOptions = [
    "AB Bank",
    "Agrani Bank",
    "Al-Arafah Islami Bank",
    "Bangladesh Bank",
    "Bangladesh Commerce Bank",
    "Bangladesh Krishi Bank",
    "Bangladesh Samabaya Bank",
    "Bangladesh Shilpa Bank",
    "Bank Al-Falah",
    "Bank Asia",
    "BASIC Bank",
    "BDBL",
    "Bengal Commercial Bank",
    "BRAC Bank",
    "Citi Bank N.A",
    "Citizen's Bank",
    "Commercial Bank of Ceylon",
    "Community Bank Bangladesh",
    "Dhaka Bank",
    "Dutch-Bangla Bank",
    "Eastern Bank",
    "EXIM Bank",
    "First Security Islami Bank",
    "Global Islami Bank",
    "Habib Bank",
    "ICB Islamic Bank",
    "IFIC Bank",
    "Islami Bank Bangladesh",
    "Jamuna Bank",
    "Janata Bank",
    "Meghna Bank",
    "Mercantile Bank",
    "Midland Bank",
    "Modhumoti Bank",
    "Mutual Trust Bank",
    "National Bank of Pakistan",
    "National Bank",
    "Commerce Bank",
    "NRB Bank",
    "NRB Commercial Bank",
    "One Bank",
    "Padma Bank",
    "Prime Bank",
    "Pubali Bank",
    "Rajshahi Krishi Unnayan Bank",
    "Rupali Bank",
    "SBAC Bank",
    "Shahjalal Islami Bank",
    "Shimanto Bank",
    "Social Islami Bank",
    "Sonali Bank",
    "Southeast Bank",
    "Standard Bank",
    "Standard Chartered Bank",
    "State Bank of India",
    "The City Bank",
    "The Premier Bank",
    "Trust Bank",
    "Union Bank",
    "United Commercial Bank",
    "Uttara Bank",
    "Woori Bank",
  ];
  
  export default bankOptions;
  