const districtAreas = {
  Dhaka: [
    "Agargaon",
    "Azimpur",
    "Adabor",
    "Aftabnagar",
    "Ashkona",
    "Islampur",
    "Eskaton Road",
    "Uttar Khan",
    "Uttara Sector-1",
    "Uttara Sector-10",
    "Uttara Sector-11",
    "Uttara Sector-12",
    "Uttara Sector-13",
    "Uttara Sector-14",
    "Uttara Sector-15",
    "Uttara Sector-3",
    "Uttara Sector-4",
    "Uttara Sector-5",
    "Uttara Sector-6",
    "Uttara Sector-7",
    "Uttara Sector-8",
    "Uttara Sector-9",
    "Elephant Road",
    "Wari",
    "Kadamtoli",
    "Kamlapur",
    "Kalabagan",
    "Kallyanpur",
    "Karwan Bazar",
    "Kawla",
    "Kathal Bagan",
    "Kafrul",
    "Kamrangirchar",
    "Kamarpara",
    "Kuril",
    "Khilkhet",
    "Khilgaon",
    "Gulshan-1",
    "Gulisthan",
    "Gendaria",
    "Goran",
    "Gopibagh",
    "Greenroad",
    "Chawkbazar",
    "Jigatola",
    "Jurain",
    "Tongi",
    "DIT Road",
    "Dumni Khilkhet",
    "Demra",
    "Dhaka Cantonment",
    "Turag",
    "Tejgaon",
    "Dhanmondi",
    "Rampura",
    "Mohammadpur",
    "Mirpur-10",
    "Mirpur-12",
    "Mirpur-13",
    "Mirpur-14",
    "Mirpur-2",
    "Mirpur-6",
    "Mugda",
    "Jatrabari",
    "Rayerbagh",
    "Rayerbazar",
    "Rupnagar",
    "Laxmibazar",
    "Lalbag",
    "Shanir Akhra",
    "Shahidnagar",
    "Shahjahanpur",
    "Shantinagar",
    "Shahjadpur",
    "Shahbag",
    "Shewrapara",
    "Shampur",
    "Shyamoli",
    "Sadarghat",
    "Satarkul",
    "Shiddeshwari",
    "Sutrapur",
    "Segunbagicha",
    "Central Road",
    "Hazaribagh",
  ],
  Chattogram: [
    "Agrabad",
    "Pahartali",
    "Halishahar",
    "Panchlaish",
    "Baizid",
    "Chawk Bazar",
  ],
  Barishal: ["Nalbari", "Kawnia", "Band Road"],
};

export default districtAreas;
